from tkinter import *
fen=Tk()
fen.title("Teste")
fen.geometry("200x200")
Button(fen, text ="arrow", relief=RAISED, cursor="arrow").pack()
Button(fen, text ="circle", relief=SUNKEN, cursor="circle").pack()
Button(fen, text ="clock", relief=RAISED, cursor="clock").pack()
Button(fen, text ="cross", relief=SUNKEN, cursor="cross").pack()
Button(fen, text ="dotbox", relief=RIDGE, cursor="dotbox").pack()
Button(fen, text ="exchange", relief=RAISED, cursor="exchange").pack()
Button(fen, text ="fleur", relief=GROOVE, cursor="fleur").pack()
Button(fen, text ="heart", relief=RAISED, cursor="heart").pack()
Button(fen, text ="man", relief=RIDGE, cursor="man").pack()
Button(fen, text ="mouse", relief=FLAT, cursor="mouse").pack()
Button(fen, text ="pirate", relief=GROOVE, cursor="pirate").pack()
Button(fen, text ="plus", relief=RAISED, cursor="plus").pack()
Button(fen, text ="shuttle", relief=RAISED, cursor="shuttle").pack()
Button(fen, text ="sizing", relief=FLAT, cursor="sizing").pack()
Button(fen, text ="spider", relief=RAISED, cursor="spider").pack()
Button(fen, text ="spraycan", relief=GROOVE, cursor="spraycan").pack()
Button(fen, text ="star", relief=RIDGE, cursor="star").pack()
Button(fen, text ="target", relief=RAISED, cursor="target").pack()
Button(fen, text ="tcross", relief=SUNKEN, cursor="tcross").pack()
Button(fen, text ="trek", relief=GROOVE, cursor="trek").pack()
Button(fen, text ="watch", relief=RAISED, cursor="watch").pack()

fen.mainloop()